name: Protect index files

on:
  pull_request:
    paths:
      - 'index.html'
      - 'index.php'

jobs:
  check-index-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: indexファイル変更チェック
        run: |
          echo "indexファイルの変更を確認中..."
          
          # 許可されたユーザー/ボットのリスト（kounosu49を除外してテスト）
          ALLOWED_USERS=("cms-bot" "github-actions[bot]")
          CURRENT_USER="${{ github.actor }}"
          
          if git diff --name-only origin/main..HEAD | grep -E "^index\.(html|php)$"; then
            echo "⚠️  indexファイルの変更を検出しました - 実行者: $CURRENT_USER"
            
            # 許可リストのユーザーかチェック
            IS_ALLOWED=false
            for user in "${ALLOWED_USERS[@]}"; do
              if [ "$CURRENT_USER" = "$user" ]; then
                IS_ALLOWED=true
                break
              fi
            done
            
            # CMS経由の更新かチェック（PRタイトルで判定）
            if [[ "${{ github.event.pull_request.title }}" == *"[CMS]"* ]] || 
               [[ "${{ github.event.pull_request.title }}" == *"cms-update"* ]]; then
              echo "✅ CMS経由の更新を検出 - 変更を許可します"
              exit 0
            fi
            
            if [ "$IS_ALLOWED" = true ]; then
              echo "✅ 承認済み: $CURRENT_USER はindexファイルを変更できます"
            else
              echo "❌ 権限エラー: 許可されたユーザー/CMSのみがindexファイルを変更できます"
              echo "許可されたユーザー: ${ALLOWED_USERS[*]}"
              echo "CMS更新の場合は、PRタイトルに[CMS]を含めてください"
              exit 1
            fi
          else
            echo "✅ indexファイルの変更はありません"
          fi